# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres_net

volumes:
  postgres_data:
    external: true

networks:
  postgres_net:
